### PR TITLE
ENHANCEMENT Support fulltext search per locale

### LINKED ISSUE #335: fluent breaks fulltextsearch
configuring basic site search (by enabling fulltextsearchable) doesn't work when fluent module is 
installed. Here's the stack strace.
https://gist.github.com/guyvanbael/d23c189dbcc181bc50c377d6a38aac7f

### PR DESCRIPTION
**Pull request by NightJar**
In order to be able to search content, we must first be able to add it
to the index. To add the content in each locale (which can vary) we must
support a Variant, much like that of the `Versioned` module. Fluent
itself takes care of modifying the query to select content, we just must
allow the Reindex task to attain and adjust it's settings.

Resolves #335

### CODE REVIEW

File: src/Search/FluentSearchVariant.php [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+use SilverStripe\FullTextSearch\Search\SearchIntrospection;
+use SilverStripe\FullTextSearch\Search\Queries\SearchQuery;
+
+class FluentSearchVariant extends SearchVariant
+{
+
+    public function appliesToEnvironment()
+    {
+        return $this->config()->get('enabled');
+    }
```
Comment (robbieaverill) [inline src/Search/FluentSearchVariant.php]: You could remove this, since `SearchVariant::appliesToEnvironment` is doing the same thing

File: src/Search/FluentSearchVariant.php [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+
+use TractorCow\Fluent\Extension\FluentExtension;
+use TractorCow\Fluent\State\FluentState;
+use TractorCow\Fluent\Model\Locale;
+use SilverStripe\ORM\DataObject;
+use SilverStripe\FullTextSearch\Search\Variants\SearchVariant;
+use SilverStripe\FullTextSearch\Search\SearchIntrospection;
+use SilverStripe\FullTextSearch\Search\Queries\SearchQuery;
+
+class FluentSearchVariant extends SearchVariant
```
Comment (robbieaverill) [inline src/Search/FluentSearchVariant.php]: We need a check here to see if `SearchVariant` exists before declaring the class. It's not ideal but this will break without FTS installed otherwise

File: src/Search/FluentSearchVariant.php [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+    public function appliesToEnvironment()
+    {
+        return $this->config()->get('enabled');
+    }
+
+    public function appliesTo($class, $includeSubclasses)
+    {
+        return $this->appliesToEnvironment() &&
+            SearchIntrospection::has_extension($class, FluentExtension::class, $includeSubclasses) &&
+            Locale::get()->count();
```
Comment (robbieaverill) [inline src/Search/FluentSearchVariant.php]: If you use `Locale::getCached()->count()` it will minimise ORM calls

File: src/Search/FluentSearchVariant.php [hunk 4]
```diff
@@ -0,0 +1,71 @@
...
+    }
+
+    public function currentState()
+    {
+        return FluentState::singleton()->getLocale();
+    }
+
+    public function reindexStates()
+    {
+        return Locale::get()->column('Locale');
```
Comment (robbieaverill) [inline src/Search/FluentSearchVariant.php]: Use `::getCached()`

File: src/Search/FluentSolrIndex.php [hunk 5]
```diff
@@ -0,0 +1,18 @@
...
+
+namespace TractorCow\Fluent\Search\Solr;
+
+use SilverStripe\FullTextSearch\Solr\SolrIndex;
+use SilverStripe\CMS\Model\SiteTree;
+
+/**
+ * Default search index
+ */
+class FluentSolrIndex extends SolrIndex
```
Comment (robbieaverill) [inline src/Search/FluentSolrIndex.php]: We don't really need this, since it is essentially a standard Solr index and is covered in the FTS documentation already

File: _config.php [hunk 6]
```diff
@@ -1,2 +1,27 @@
...
+            // Allow storing the solr index and config data in an arbitrary location,
+            // e.g. outside of the webroot
+            'path' => Environment::getEnv('SOLR_INDEXSTORE_PATH')
+                ? Environment::getEnv('SOLR_INDEXSTORE_PATH')
+                : BASE_PATH . '/.solr',
+            'remotepath' => Environment::getEnv('SOLR_REMOTE_PATH')
+                ? Environment::getEnv('SOLR_REMOTE_PATH')
+                : null
+        ]
+    ]);
```
Comment (robbieaverill) [inline _config.php]: As discussed in standup - remove this autoconfig logic

File: src/Search/FluentSearchVariant.php [hunk 7]
```diff
@@ -0,0 +1,69 @@
...
+use SilverStripe\ORM\DataObject;
+use SilverStripe\FullTextSearch\Search\Variants\SearchVariant;
+use SilverStripe\FullTextSearch\Search\SearchIntrospection;
+use SilverStripe\FullTextSearch\Search\Queries\SearchQuery;
+
+if (!class_exists(SearchVariant::class)) {
+    return;
+}
+
+class FluentSearchVariant extends SearchVariant
```
Comment (robbieaverill) [inline src/Search/FluentSearchVariant.php]: Maybe adding a doc block might be useful to explain what it does at a high level?

Comment (NightJar) [reply src/Search/FluentSearchVariant.php]: Sounds ideal.

Comment (NightJar) [reply src/Search/FluentSearchVariant.php]: Done :)

**Comment by robbieaverill** [comment]
mog

**Comment by NightJar** [comment]
54zdierl g3w
moggie, emerging green.
