### PR TITLE
BUG Fix invalid locale being set for domain mode

### LINKED ISSUE #419: Domain setup triggers invalid locale error
Potentially stumbled across an issue during some experimenting that was also reported by another user in the #translations channel in SilverStripe Users slack earlier in the month.

After attaching a unique domain to each of my locales, ensuring there is default locale for each domain and lastly setting `SS_FLUENT_FORCE_DOMAIN=true`,  I am greeted by the following error on the frontend on all but home page: `[Emergency] Uncaught InvalidArgumentException: Invalid "TractorCow\Fluent\Model\Locale" locale.`.

While the home page loads ok, it only uses the global default locale regardless of the domain.

Configuration is all default but I did try setting `disable_default_prefix` to `true` to see if that helped at all.

Everything works as expected when no domains are in play.

```
silverstripe/cms 4.1.0
silverstripe/framework 4.1.0
tractorcow/silverstripe-fluent 4.1.0 
```

### PR DESCRIPTION
**Pull request by tractorcow**
Fixes #419 

Merge up to 4.1 and so on after merge.

### CODE REVIEW

**Comment by robbieaverill** [comment]
Need to target 4.0 branch in order to merge up to 4.1?

File: src/State/FluentState.php [hunk 1]
```diff
@@ -75,11 +79,14 @@ public function getDomain()
     /**
      * Set the current domain code
      *
-     * @param string $domain
+     * @param string|null $domain
      * @return $this
```
Comment (robbieaverill) [inline src/State/FluentState.php]: Can we add some PHPDocs for the exceptions this throws?

Comment (tractorcow) [reply src/State/FluentState.php]: We don't really do that in core; It could be a standard, but I'd probably wait until we did it consistently before adding it to other modules.

And then, I'd do it everywhere of course. :)

Comment (robbieaverill) [reply src/State/FluentState.php]: Oh? Ok 😆

**Comment by robbieaverill** [comment]
Re-target at 4.0 branch if needed before merge

**Comment by tractorcow** [comment]
oh oops.

**Comment by tractorcow** [comment]
Fixed.

**Comment by robbieaverill** [comment]
@tractorcow I'll merge up now
