### PR TITLE
WIP: FIX Implement localisable order by clause to support translatable sorting

### LINKED ISSUE #208: sort() is not working on translated fields
Sorting of translated fields is not working:

`$this->Tags()->sort('Title', 'ASC');`
Does only work on default locale, because sort is ALWAYS sorting Tags on default locale instead of current locale.

```
$Loc_TitleField = Fluent::db_field_for_locale('Title', $this->CurrentLocale());
$this->Tags()->sort($Loc_TitleField, 'ASC');
```

Is not working, because Tags that have no textual difference in translation, are `null` in the database and therefore mess up the sort.

### PR DESCRIPTION
**Pull request by robbieaverill**
Resolves #208

### CODE REVIEW

**Comment by robbieaverill** [comment]
I've implemented a rough looking fix to allow localisable sort conditions in the same way that localisable where conditions work at the moment. There's a test failure in `testWritesToCurrentLocale` which looks to be pre-existing (tested locally on 4.1, re-running the last 4.1 build on Travis now).

@tractorcow would be good to get your eyes over this when you're back from your holiday =)

**Comment by robbieaverill** [comment]
Ok so the tests I added in the first commit broke the `testWritesToCurrentLocale` test - I'll work out why and push an update

File: src/Extension/FluentExtension.php [hunk 1]
```diff
@@ -389,9 +389,59 @@ public function augmentSQL(SQLSelect $query, DataQuery $dataQuery = null)
...
+            // Look for table context
+            if (preg_match('/^"(?<table>[\w\\\\]+)"\."(?<field>\w+)"$/i', $column, $matches)) {
+                $field = $matches['field'];
+            } else {
+                // If no table context is given, see if we can find one in the select
+                // e.g. "Title" -> "SomeTable"."Title"
+                $foundInConditionSearch = false;
+                foreach ($conditionSearch as $conditionSearchOption) {
+                    if (preg_match(
+                        '/^"(?<table>[\w\\\\]+)"\."(?<field>' . trim($column, '"') . ')"$/i',
```
Comment (tractorcow) [inline src/Extension/FluentExtension.php]: If $column fails the above regexp, I think assuming that it's a basic column name is a bit risky. It could be a non-trivial sub-query, or it could be a composite sort. The `else` should really be another regexp that is similar but doesn't require the table prefix.

Comment (robbieaverill) [reply src/Extension/FluentExtension.php]: Ok, do you have a couple of examples that I could add to the tests?

Comment (tractorcow) [reply src/Extension/FluentExtension.php]: like `$list->sort('"Title", "Content"')`

Comment (robbieaverill) [reply src/Extension/FluentExtension.php]: Sweet. We can't really make subqueries fluent in this case though right...?

Comment (tractorcow) [reply src/Extension/FluentExtension.php]: Right so you should skip them.

Comment (robbieaverill) [reply src/Extension/FluentExtension.php]: I've added a bunch more tests, the last commit contains some tests that I've got no idea how to write logic for to make them pass 😆 

Also I'm a bit iffy about some of the tests in the "Add more sorting tests" commit because they're relying on the DB to return natural sort orders when the sorting isn't specific enough to always return a definite order - the fixtures have common values in them (deliberately) but maybe we either need to remove the common values to ensure that there's a predictable sort order at all times.

**Comment by tractorcow** [comment]
Pushed up some fixes @robbieaverill

**Comment by tractorcow** [comment]
Pushed up linting fixes @robbieaverill but there are still some small issues to fix.

**Comment by chrispenny** [comment]
I'm late to the party on this one, but please accept my delayed:
Thank you! I appreciate your work (as always)!

**Comment by lerni** [comment]
If you experience this issue with SS 3.x theres a composer installable patch https://github.com/lerni/silverstripe3-mysql57-fluent
